// Auto-generated from U.S. Dept. of Education College Scorecard data (2017-18).
// 617 non-metro college towns, >=3,000 residential (non-online, non-commuter) students.
// Gateway markets (NYC, LA, Chicago, SF, Boston, DC, Miami, Seattle) explicitly
// excluded even where a large university sits inside them (e.g. Harvard/Cambridge).
// Regenerate via the data pipeline, do not hand-edit entries.

export interface CollegeTownMatch {
  city: string
  state: string
  students: number
  institution: string
}

const COLLEGE_TOWNS: Record<string, CollegeTownMatch> = {
  'anchorage|ak': { city: 'Anchorage', state: 'AK', students: 12009, institution: 'University of Alaska Anchorage' },
  'fairbanks|ak': { city: 'Fairbanks', state: 'AK', students: 4910, institution: 'University of Alaska Fairbanks' },
  'tuscaloosa|al': { city: 'Tuscaloosa', state: 'AL', students: 33070, institution: 'The University of Alabama' },
  'auburn|al': { city: 'Auburn', state: 'AL', students: 23391, institution: 'Auburn University' },
  'mobile|al': { city: 'Mobile', state: 'AL', students: 14886, institution: 'University of South Alabama' },
  'troy|al': { city: 'Troy', state: 'AL', students: 13634, institution: 'Troy University' },
  'montgomery|al': { city: 'Montgomery', state: 'AL', students: 13409, institution: 'Auburn University at Montgomery' },
  'huntsville|al': { city: 'Huntsville', state: 'AL', students: 9365, institution: 'University of Alabama in Huntsville' },
  'florence|al': { city: 'Florence', state: 'AL', students: 5830, institution: 'University of North Alabama' },
  'normal|al': { city: 'Normal', state: 'AL', students: 4824, institution: 'Alabama A & M University' },
  'fayetteville|ar': { city: 'Fayetteville', state: 'AR', students: 23097, institution: 'University of Arkansas' },
  'conway|ar': { city: 'Conway', state: 'AR', students: 11013, institution: 'University of Central Arkansas' },
  'jonesboro|ar': { city: 'Jonesboro', state: 'AR', students: 8921, institution: 'Arkansas State University-Main Campus' },
  'russellville|ar': { city: 'Russellville', state: 'AR', students: 8289, institution: 'Arkansas Tech University' },
  'fort smith|ar': { city: 'Fort Smith', state: 'AR', students: 5554, institution: 'University of Arkansas-Fort Smith' },
  'arkadelphia|ar': { city: 'Arkadelphia', state: 'AR', students: 4342, institution: 'Henderson State University' },
  'searcy|ar': { city: 'Searcy', state: 'AR', students: 4214, institution: 'Harding University' },
  'pine bluff|ar': { city: 'Pine Bluff', state: 'AR', students: 3679, institution: 'University of Arkansas at Pine Bluff' },
  'magnolia|ar': { city: 'Magnolia', state: 'AR', students: 3153, institution: 'Southern Arkansas University Main Campus' },
  'flagstaff|az': { city: 'Flagstaff', state: 'AZ', students: 27089, institution: 'Northern Arizona University' },
  'prescott|az': { city: 'Prescott', state: 'AZ', students: 7630, institution: 'Yavapai College' },
  'yuma|az': { city: 'Yuma', state: 'AZ', students: 6879, institution: 'Arizona Western College' },
  'coolidge|az': { city: 'Coolidge', state: 'AZ', students: 4822, institution: 'Central Arizona College' },
  'thatcher|az': { city: 'Thatcher', state: 'AZ', students: 3729, institution: 'Eastern Arizona College' },
  'santa barbara|ca': { city: 'Santa Barbara', state: 'CA', students: 36913, institution: 'University of California-Santa Barbara' },
  'san bernardino|ca': { city: 'San Bernardino', state: 'CA', students: 31385, institution: 'California State University-San Bernardino' },
  'san luis obispo|ca': { city: 'San Luis Obispo', state: 'CA', students: 30545, institution: 'California Polytechnic State University-San Luis Obispo' },
  'davis|ca': { city: 'Davis', state: 'CA', students: 30046, institution: 'University of California-Davis' },
  'monterey park|ca': { city: 'Monterey Park', state: 'CA', students: 29896, institution: 'East Los Angeles College' },
  'bakersfield|ca': { city: 'Bakersfield', state: 'CA', students: 29362, institution: 'Bakersfield College' },
  'walnut|ca': { city: 'Walnut', state: 'CA', students: 26865, institution: 'Mt San Antonio College' },
  'el cajon|ca': { city: 'El Cajon', state: 'CA', students: 24533, institution: 'Grossmont College' },
  'costa mesa|ca': { city: 'Costa Mesa', state: 'CA', students: 23448, institution: 'Orange Coast College' },
  'rancho cucamonga|ca': { city: 'Rancho Cucamonga', state: 'CA', students: 19897, institution: 'Chaffey College' },
  'whittier|ca': { city: 'Whittier', state: 'CA', students: 19544, institution: 'Rio Hondo College' },
  'santa clarita|ca': { city: 'Santa Clarita', state: 'CA', students: 18999, institution: 'College of the Canyons' },
  'orange|ca': { city: 'Orange', state: 'CA', students: 18788, institution: 'Santiago Canyon College' },
  'pleasant hill|ca': { city: 'Pleasant Hill', state: 'CA', students: 18572, institution: 'Diablo Valley College' },
  'chula vista|ca': { city: 'Chula Vista', state: 'CA', students: 18243, institution: 'Southwestern College' },
  'cupertino|ca': { city: 'Cupertino', state: 'CA', students: 18183, institution: 'De Anza College' },
  'mission viejo|ca': { city: 'Mission Viejo', state: 'CA', students: 17843, institution: 'Saddleback College' },
  'merced|ca': { city: 'Merced', state: 'CA', students: 17679, institution: 'Merced College' },
  'santa cruz|ca': { city: 'Santa Cruz', state: 'CA', students: 17611, institution: 'University of California-Santa Cruz' },
  'rocklin|ca': { city: 'Rocklin', state: 'CA', students: 17571, institution: 'Sierra College' },
  'visalia|ca': { city: 'Visalia', state: 'CA', students: 16892, institution: 'College of the Sequoias' },
  'norwalk|ca': { city: 'Norwalk', state: 'CA', students: 16789, institution: 'Cerritos College' },
  'woodland hills|ca': { city: 'Woodland Hills', state: 'CA', students: 16439, institution: 'Los Angeles Pierce College' },
  'valley glen|ca': { city: 'Valley Glen', state: 'CA', students: 14631, institution: 'Los Angeles Valley College' },
  'cypress|ca': { city: 'Cypress', state: 'CA', students: 14434, institution: 'Cypress College' },
  'los altos hills|ca': { city: 'Los Altos Hills', state: 'CA', students: 13873, institution: 'Foothill College' },
  'oceanside|ca': { city: 'Oceanside', state: 'CA', students: 13808, institution: 'MiraCosta College' },
  'lancaster|ca': { city: 'Lancaster', state: 'CA', students: 13464, institution: 'Antelope Valley College' },
  'moorpark|ca': { city: 'Moorpark', state: 'CA', students: 13378, institution: 'Moorpark College' },
  'ventura|ca': { city: 'Ventura', state: 'CA', students: 12385, institution: 'Ventura College' },
  'santa clara|ca': { city: 'Santa Clara', state: 'CA', students: 12061, institution: 'Mission College' },
  'glendora|ca': { city: 'Glendora', state: 'CA', students: 11629, institution: 'Citrus College' },
  'salinas|ca': { city: 'Salinas', state: 'CA', students: 11499, institution: 'Hartnell College' },
  'huntington beach|ca': { city: 'Huntington Beach', state: 'CA', students: 10856, institution: 'Golden West College' },
  'fremont|ca': { city: 'Fremont', state: 'CA', students: 10741, institution: 'Ohlone College' },
  'aptos|ca': { city: 'Aptos', state: 'CA', students: 10556, institution: 'Cabrillo College' },
  'palm desert|ca': { city: 'Palm Desert', state: 'CA', students: 10351, institution: 'College of the Desert' },
  'oroville|ca': { city: 'Oroville', state: 'CA', students: 10188, institution: 'Butte College' },
  'culver city|ca': { city: 'Culver City', state: 'CA', students: 9815, institution: 'West Los Angeles College' },
  'victorville|ca': { city: 'Victorville', state: 'CA', students: 9534, institution: 'Victor Valley College' },
  'santa maria|ca': { city: 'Santa Maria', state: 'CA', students: 9497, institution: 'Allan Hancock College' },
  'san mateo|ca': { city: 'San Mateo', state: 'CA', students: 9377, institution: 'College of San Mateo' },
  'norco|ca': { city: 'Norco', state: 'CA', students: 8647, institution: 'Norco College' },
  'redding|ca': { city: 'Redding', state: 'CA', students: 8641, institution: 'Shasta College' },
  'rohnert park|ca': { city: 'Rohnert Park', state: 'CA', students: 8633, institution: 'Sonoma State University' },
  'reedley|ca': { city: 'Reedley', state: 'CA', students: 8624, institution: 'Reedley College' },
  'sylmar|ca': { city: 'Sylmar', state: 'CA', students: 8624, institution: 'Los Angeles Mission College' },
  'pittsburg|ca': { city: 'Pittsburg', state: 'CA', students: 8110, institution: 'Los Medanos College' },
  'moreno valley|ca': { city: 'Moreno Valley', state: 'CA', students: 8087, institution: 'Moreno Valley College' },
  'san bruno|ca': { city: 'San Bruno', state: 'CA', students: 8084, institution: 'Skyline College' },
  'livermore|ca': { city: 'Livermore', state: 'CA', students: 8077, institution: 'Las Positas College' },
  'folsom|ca': { city: 'Folsom', state: 'CA', students: 7911, institution: 'Folsom Lake College' },
  'arcata|ca': { city: 'Arcata', state: 'CA', students: 7846, institution: 'Humboldt State University' },
  'imperial|ca': { city: 'Imperial', state: 'CA', students: 7360, institution: 'Imperial Valley College' },
  'wilmington|ca': { city: 'Wilmington', state: 'CA', students: 7354, institution: 'Los Angeles Harbor College' },
  'stanford|ca': { city: 'Stanford', state: 'CA', students: 7056, institution: 'Stanford University' },
  'camarillo|ca': { city: 'Camarillo', state: 'CA', students: 7047, institution: 'California State University-Channel Islands' },
  'oxnard|ca': { city: 'Oxnard', state: 'CA', students: 6966, institution: 'Oxnard College' },
  'monterey|ca': { city: 'Monterey', state: 'CA', students: 6869, institution: 'Monterey Peninsula College' },
  'saratoga|ca': { city: 'Saratoga', state: 'CA', students: 6799, institution: 'West Valley College' },
  'seaside|ca': { city: 'Seaside', state: 'CA', students: 6557, institution: 'California State University-Monterey Bay' },
  'compton|ca': { city: 'Compton', state: 'CA', students: 6212, institution: 'Compton College' },
  'claremont|ca': { city: 'Claremont', state: 'CA', students: 5878, institution: 'Pomona College' },
  'taft|ca': { city: 'Taft', state: 'CA', students: 5704, institution: 'Taft College' },
  'azusa|ca': { city: 'Azusa', state: 'CA', students: 5560, institution: 'Azusa Pacific University' },
  'yucaipa|ca': { city: 'Yucaipa', state: 'CA', students: 5373, institution: 'Crafton Hills College' },
  'san pablo|ca': { city: 'San Pablo', state: 'CA', students: 5372, institution: 'Contra Costa College' },
  'napa|ca': { city: 'Napa', state: 'CA', students: 5295, institution: 'Napa Valley College' },
  'hollywood|ca': { city: 'Hollywood', state: 'CA', students: 5231, institution: 'Los Angeles Film School' },
  'la verne|ca': { city: 'La Verne', state: 'CA', students: 5120, institution: 'University of La Verne' },
  'gilroy|ca': { city: 'Gilroy', state: 'CA', students: 5013, institution: 'Gavilan College' },
  'redwood city|ca': { city: 'Redwood City', state: 'CA', students: 4996, institution: 'Canada College' },
  'marysville|ca': { city: 'Marysville', state: 'CA', students: 4889, institution: 'Yuba College' },
  'alameda|ca': { city: 'Alameda', state: 'CA', students: 4673, institution: 'College of Alameda' },
  'kentfield|ca': { city: 'Kentfield', state: 'CA', students: 4190, institution: 'College of Marin' },
  'la mirada|ca': { city: 'La Mirada', state: 'CA', students: 4039, institution: 'Biola University' },
  'eureka|ca': { city: 'Eureka', state: 'CA', students: 3938, institution: 'College of the Redwoods' },
  'lemoore|ca': { city: 'Lemoore', state: 'CA', students: 3843, institution: 'West Hills College-Lemoore' },
  'la puente|ca': { city: 'La Puente', state: 'CA', students: 3758, institution: 'Hacienda La Puente Adult Education' },
  'ontario|ca': { city: 'Ontario', state: 'CA', students: 3758, institution: 'American Career College-Ontario' },
  'malibu|ca': { city: 'Malibu', state: 'CA', students: 3594, institution: 'Pepperdine University' },
  'blythe|ca': { city: 'Blythe', state: 'CA', students: 3496, institution: 'Palo Verde College' },
  'north hollywood|ca': { city: 'North Hollywood', state: 'CA', students: 3326, institution: 'West Coast University-Los Angeles' },
  'porterville|ca': { city: 'Porterville', state: 'CA', students: 3304, institution: 'Porterville College' },
  'redlands|ca': { city: 'Redlands', state: 'CA', students: 3184, institution: 'University of Redlands' },
  'coalinga|ca': { city: 'Coalinga', state: 'CA', students: 3031, institution: 'West Hills College-Coalinga' },
  'ukiah|ca': { city: 'Ukiah', state: 'CA', students: 3020, institution: 'Mendocino College' },
  'boulder|co': { city: 'Boulder', state: 'CO', students: 30117, institution: 'University of Colorado Boulder' },
  'fort collins|co': { city: 'Fort Collins', state: 'CO', students: 24343, institution: 'Colorado State University-Fort Collins' },
  'grand junction|co': { city: 'Grand Junction', state: 'CO', students: 9398, institution: 'Colorado Mesa University' },
  'greeley|co': { city: 'Greeley', state: 'CO', students: 9154, institution: 'University of Northern Colorado' },
  'greenwood village|co': { city: 'Greenwood Village', state: 'CO', students: 8035, institution: 'Colorado State University-Global Campus' },
  'lakewood|co': { city: 'Lakewood', state: 'CO', students: 6429, institution: 'Colorado Christian University' },
  'golden|co': { city: 'Golden', state: 'CO', students: 4751, institution: 'Colorado School of Mines' },
  'usaf academy|co': { city: 'Usaf Academy', state: 'CO', students: 4276, institution: 'United States Air Force Academy' },
  'pueblo|co': { city: 'Pueblo', state: 'CO', students: 3744, institution: 'Colorado State University-Pueblo' },
  'glenwood springs|co': { city: 'Glenwood Springs', state: 'CO', students: 3511, institution: 'Colorado Mountain College' },
  'durango|co': { city: 'Durango', state: 'CO', students: 3150, institution: 'Fort Lewis College' },
  'storrs|ct': { city: 'Storrs', state: 'CT', students: 18930, institution: 'University of Connecticut' },
  'new haven|ct': { city: 'New Haven', state: 'CT', students: 14567, institution: 'Southern Connecticut State University' },
  'new britain|ct': { city: 'New Britain', state: 'CT', students: 10669, institution: 'Central Connecticut State University' },
  'fairfield|ct': { city: 'Fairfield', state: 'CT', students: 9519, institution: 'Sacred Heart University' },
  'waterbury|ct': { city: 'Waterbury', state: 'CT', students: 9053, institution: 'Post University' },
  'hamden|ct': { city: 'Hamden', state: 'CT', students: 7319, institution: 'Quinnipiac University' },
  'west hartford|ct': { city: 'West Hartford', state: 'CT', students: 5999, institution: 'University of Hartford' },
  'west haven|ct': { city: 'West Haven', state: 'CT', students: 5728, institution: 'University of New Haven' },
  'danbury|ct': { city: 'Danbury', state: 'CT', students: 5113, institution: 'Western Connecticut State University' },
  'willimantic|ct': { city: 'Willimantic', state: 'CT', students: 4669, institution: 'Eastern Connecticut State University' },
  'bridgeport|ct': { city: 'Bridgeport', state: 'CT', students: 3801, institution: 'University of Bridgeport' },
  'east hartford|ct': { city: 'East Hartford', state: 'CT', students: 3657, institution: 'Goodwin College' },
  'new castle|de': { city: 'New Castle', state: 'DE', students: 8346, institution: 'Wilmington University' },
  'dover|de': { city: 'Dover', state: 'DE', students: 5246, institution: 'Delaware State University' },
  'gainesville|fl': { city: 'Gainesville', state: 'FL', students: 49782, institution: 'University of Florida' },
  'tallahassee|fl': { city: 'Tallahassee', state: 'FL', students: 41935, institution: 'Florida State University' },
  'daytona beach|fl': { city: 'Daytona Beach', state: 'FL', students: 30742, institution: 'Daytona State College' },
  'boca raton|fl': { city: 'Boca Raton', state: 'FL', students: 28126, institution: 'Florida Atlantic University' },
  'fort myers|fl': { city: 'Fort Myers', state: 'FL', students: 26977, institution: 'Florida Gulf Coast University' },
  'clearwater|fl': { city: 'Clearwater', state: 'FL', students: 26938, institution: 'St Petersburg College' },
  'lake worth|fl': { city: 'Lake Worth', state: 'FL', students: 26335, institution: 'Palm Beach State College' },
  'pensacola|fl': { city: 'Pensacola', state: 'FL', students: 18329, institution: 'The University of West Florida' },
  'sanford|fl': { city: 'Sanford', state: 'FL', students: 15740, institution: 'Seminole State College of Florida' },
  'ocala|fl': { city: 'Ocala', state: 'FL', students: 14067, institution: 'Rasmussen College-Florida' },
  'fort pierce|fl': { city: 'Fort Pierce', state: 'FL', students: 14040, institution: 'Indian River State College' },
  'cocoa|fl': { city: 'Cocoa', state: 'FL', students: 12306, institution: 'Eastern Florida State College' },
  'coral gables|fl': { city: 'Coral Gables', state: 'FL', students: 10613, institution: 'University of Miami' },
  'new port richey|fl': { city: 'New Port Richey', state: 'FL', students: 9641, institution: 'Pasco-Hernando State College' },
  'saint leo|fl': { city: 'Saint Leo', state: 'FL', students: 9404, institution: 'Saint Leo University' },
  'lakeland|fl': { city: 'Lakeland', state: 'FL', students: 9007, institution: 'Southeastern University' },
  'bradenton|fl': { city: 'Bradenton', state: 'FL', students: 8493, institution: 'State College of Florida-Manatee-Sarasota' },
  'winter haven|fl': { city: 'Winter Haven', state: 'FL', students: 8388, institution: 'Polk State College' },
  'melbourne|fl': { city: 'Melbourne', state: 'FL', students: 5131, institution: 'Florida Institute of Technology' },
  'west palm beach|fl': { city: 'West Palm Beach', state: 'FL', students: 4884, institution: 'Palm Beach Atlantic University' },
  'palatka|fl': { city: 'Palatka', state: 'FL', students: 4777, institution: 'Saint Johns River State College' },
  'sarasota|fl': { city: 'Sarasota', state: 'FL', students: 4625, institution: 'University of South Florida-Sarasota-Manatee' },
  'panama city|fl': { city: 'Panama City', state: 'FL', students: 4450, institution: 'Gulf Coast State College' },
  'st. petersburg|fl': { city: 'St. Petersburg', state: 'FL', students: 4342, institution: 'University of South Florida-St Petersburg' },
  'leesburg|fl': { city: 'Leesburg', state: 'FL', students: 4122, institution: 'Lake-Sumter State College' },
  'niceville|fl': { city: 'Niceville', state: 'FL', students: 4075, institution: 'Northwest Florida State College' },
  'saint petersburg|fl': { city: 'Saint Petersburg', state: 'FL', students: 3366, institution: 'Eckerd College' },
  'winter park|fl': { city: 'Winter Park', state: 'FL', students: 3185, institution: 'Rollins College' },
  'deland|fl': { city: 'Deland', state: 'FL', students: 3031, institution: 'Stetson University' },
  'kennesaw|ga': { city: 'Kennesaw', state: 'GA', students: 32486, institution: 'Kennesaw State University' },
  'athens|ga': { city: 'Athens', state: 'GA', students: 29077, institution: 'University of Georgia' },
  'savannah|ga': { city: 'Savannah', state: 'GA', students: 25779, institution: 'Savannah College of Art and Design' },
  'dahlonega|ga': { city: 'Dahlonega', state: 'GA', students: 17067, institution: 'University of North Georgia' },
  'statesboro|ga': { city: 'Statesboro', state: 'GA', students: 17062, institution: 'Georgia Southern University' },
  'macon|ga': { city: 'Macon', state: 'GA', students: 12758, institution: 'Middle Georgia State University' },
  'lawrenceville|ga': { city: 'Lawrenceville', state: 'GA', students: 11916, institution: 'Georgia Gwinnett College' },
  'milledgeville|ga': { city: 'Milledgeville', state: 'GA', students: 11804, institution: 'Georgia Military College' },
  'carrollton|ga': { city: 'Carrollton', state: 'GA', students: 10468, institution: 'University of West Georgia' },
  'valdosta|ga': { city: 'Valdosta', state: 'GA', students: 8557, institution: 'Valdosta State University' },
  'rome|ga': { city: 'Rome', state: 'GA', students: 7092, institution: 'Georgia Highlands College' },
  'augusta|ga': { city: 'Augusta', state: 'GA', students: 6696, institution: 'Augusta University' },
  'morrow|ga': { city: 'Morrow', state: 'GA', students: 6558, institution: 'Clayton  State University' },
  'dalton|ga': { city: 'Dalton', state: 'GA', students: 4887, institution: 'Dalton State College' },
  'barnesville|ga': { city: 'Barnesville', state: 'GA', students: 3527, institution: 'Gordon State College' },
  'brunswick|ga': { city: 'Brunswick', state: 'GA', students: 3190, institution: 'College of Coastal Georgia' },
  'tifton|ga': { city: 'Tifton', state: 'GA', students: 3185, institution: 'Abraham Baldwin Agricultural College' },
  'mangilao|gu': { city: 'Mangilao', state: 'GU', students: 3586, institution: 'University of Guam' },
  'ames|ia': { city: 'Ames', state: 'IA', students: 30211, institution: 'Iowa State University' },
  'iowa city|ia': { city: 'Iowa City', state: 'IA', students: 23412, institution: 'University of Iowa' },
  'cedar falls|ia': { city: 'Cedar Falls', state: 'IA', students: 9759, institution: 'University of Northern Iowa' },
  'dubuque|ia': { city: 'Dubuque', state: 'IA', students: 4495, institution: 'University of Dubuque' },
  'fayette|ia': { city: 'Fayette', state: 'IA', students: 4058, institution: 'Upper Iowa University' },
  'cedar rapids|ia': { city: 'Cedar Rapids', state: 'IA', students: 3019, institution: 'Mount Mercy University' },
  'rexburg|id': { city: 'Rexburg', state: 'ID', students: 35214, institution: 'Brigham Young University-Idaho' },
  'nampa|id': { city: 'Nampa', state: 'ID', students: 8072, institution: 'College of Western Idaho' },
  'pocatello|id': { city: 'Pocatello', state: 'ID', students: 7921, institution: 'Idaho State University' },
  'moscow|id': { city: 'Moscow', state: 'ID', students: 7834, institution: 'University of Idaho' },
  'coeur d\'alene|id': { city: 'Coeur D\'Alene', state: 'ID', students: 3794, institution: 'North Idaho College' },
  'twin falls|id': { city: 'Twin Falls', state: 'ID', students: 3762, institution: 'College of Southern Idaho' },
  'champaign|il': { city: 'Champaign', state: 'IL', students: 38531, institution: 'University of Illinois at Urbana-Champaign' },
  'normal|il': { city: 'Normal', state: 'IL', students: 18392, institution: 'Illinois State University' },
  'glen ellyn|il': { city: 'Glen Ellyn', state: 'IL', students: 16628, institution: 'College of DuPage' },
  'addison|il': { city: 'Addison', state: 'IL', students: 15689, institution: 'Chamberlain University-Illinois' },
  'dekalb|il': { city: 'Dekalb', state: 'IL', students: 13497, institution: 'Northern Illinois University' },
  'edwardsville|il': { city: 'Edwardsville', state: 'IL', students: 11339, institution: 'Southern Illinois University-Edwardsville' },
  'palatine|il': { city: 'Palatine', state: 'IL', students: 11027, institution: 'William Rainey Harper College' },
  'carbondale|il': { city: 'Carbondale', state: 'IL', students: 10896, institution: 'Southern Illinois University-Carbondale' },
  'grayslake|il': { city: 'Grayslake', state: 'IL', students: 10415, institution: 'College of Lake County' },
  'schaumburg|il': { city: 'Schaumburg', state: 'IL', students: 9376, institution: 'American InterContinental University' },
  'rockford|il': { city: 'Rockford', state: 'IL', students: 9343, institution: 'Rock Valley College' },
  'evanston|il': { city: 'Evanston', state: 'IL', students: 8511, institution: 'Northwestern University' },
  'river grove|il': { city: 'River Grove', state: 'IL', students: 8073, institution: 'Triton College' },
  'macomb|il': { city: 'Macomb', state: 'IL', students: 7599, institution: 'Western Illinois University' },
  'belleville|il': { city: 'Belleville', state: 'IL', students: 7299, institution: 'Southwestern Illinois College' },
  'east peoria|il': { city: 'East Peoria', state: 'IL', students: 6921, institution: 'Illinois Central College' },
  'peoria|il': { city: 'Peoria', state: 'IL', students: 6116, institution: 'Bradley University' },
  'charleston|il': { city: 'Charleston', state: 'IL', students: 4877, institution: 'Eastern Illinois University' },
  'romeoville|il': { city: 'Romeoville', state: 'IL', students: 4372, institution: 'Lewis University' },
  'bourbonnais|il': { city: 'Bourbonnais', state: 'IL', students: 3661, institution: 'Olivet Nazarene University' },
  'chicago heights|il': { city: 'Chicago Heights', state: 'IL', students: 3573, institution: 'Prairie State College' },
  'river forest|il': { city: 'River Forest', state: 'IL', students: 3560, institution: 'Dominican University' },
  'cicero|il': { city: 'Cicero', state: 'IL', students: 3486, institution: 'Morton College' },
  'mattoon|il': { city: 'Mattoon', state: 'IL', students: 3332, institution: 'Lake Land College' },
  'university park|il': { city: 'University Park', state: 'IL', students: 3288, institution: 'Governors State University' },
  'moline|il': { city: 'Moline', state: 'IL', students: 3256, institution: 'Black Hawk College' },
  'springfield|il': { city: 'Springfield', state: 'IL', students: 3234, institution: 'University of Illinois at Springfield' },
  'carterville|il': { city: 'Carterville', state: 'IL', students: 3049, institution: 'John A Logan College' },
  'bloomington|in': { city: 'Bloomington', state: 'IN', students: 33172, institution: 'Indiana University-Bloomington' },
  'west lafayette|in': { city: 'West Lafayette', state: 'IN', students: 31887, institution: 'Purdue University-Main Campus' },
  'muncie|in': { city: 'Muncie', state: 'IN', students: 16365, institution: 'Ball State University' },
  'terre haute|in': { city: 'Terre Haute', state: 'IN', students: 13018, institution: 'Indiana State University' },
  'south bend|in': { city: 'South Bend', state: 'IN', students: 4834, institution: 'Indiana University-South Bend' },
  'evansville|in': { city: 'Evansville', state: 'IN', students: 9909, institution: 'University of Southern Indiana' },
  'marion|in': { city: 'Marion', state: 'IN', students: 9234, institution: 'Indiana Wesleyan University-National & Global' },
  'hammond|in': { city: 'Hammond', state: 'IN', students: 8963, institution: 'Purdue University Northwest' },
  'vincennes|in': { city: 'Vincennes', state: 'IN', students: 6826, institution: 'Vincennes University' },
  'new albany|in': { city: 'New Albany', state: 'IN', students: 4722, institution: 'Indiana University-Southeast' },
  'gary|in': { city: 'Gary', state: 'IN', students: 3634, institution: 'Indiana University-Northwest' },
  'valparaiso|in': { city: 'Valparaiso', state: 'IN', students: 3460, institution: 'Valparaiso University' },
  'lawrence|ks': { city: 'Lawrence', state: 'KS', students: 19733, institution: 'University of Kansas' },
  'manhattan|ks': { city: 'Manhattan', state: 'KS', students: 18644, institution: 'Kansas State University' },
  'hays|ks': { city: 'Hays', state: 'KS', students: 12230, institution: 'Fort Hays State University' },
  'lenexa|ks': { city: 'Lenexa', state: 'KS', students: 7771, institution: 'Grantham University' },
  'topeka|ks': { city: 'Topeka', state: 'KS', students: 6713, institution: 'Washburn University' },
  'pittsburg|ks': { city: 'Pittsburg', state: 'KS', students: 5340, institution: 'Pittsburg State University' },
  'emporia|ks': { city: 'Emporia', state: 'KS', students: 3499, institution: 'Emporia State University' },
  'lexington|ky': { city: 'Lexington', state: 'KY', students: 23652, institution: 'University of Kentucky' },
  'bowling green|ky': { city: 'Bowling Green', state: 'KY', students: 15262, institution: 'Western Kentucky University' },
  'highland heights|ky': { city: 'Highland Heights', state: 'KY', students: 10728, institution: 'Northern Kentucky University' },
  'murray|ky': { city: 'Murray', state: 'KY', students: 7218, institution: 'Murray State University' },
  'morehead|ky': { city: 'Morehead', state: 'KY', students: 6410, institution: 'Morehead State University' },
  'lafayette|la': { city: 'Lafayette', state: 'LA', students: 16200, institution: 'University of Louisiana at Lafayette' },
  'hammond|la': { city: 'Hammond', state: 'LA', students: 11152, institution: 'Southeastern Louisiana University' },
  'ruston|la': { city: 'Ruston', state: 'LA', students: 8310, institution: 'Louisiana Tech University' },
  'natchitoches|la': { city: 'Natchitoches', state: 'LA', students: 7994, institution: 'Northwestern State University of Louisiana' },
  'monroe|la': { city: 'Monroe', state: 'LA', students: 6805, institution: 'University of Louisiana at Monroe' },
  'lake charles|la': { city: 'Lake Charles', state: 'LA', students: 6241, institution: 'McNeese State University' },
  'shreveport|la': { city: 'Shreveport', state: 'LA', students: 6066, institution: 'Louisiana State University-Shreveport' },
  'thibodaux|la': { city: 'Thibodaux', state: 'LA', students: 5401, institution: 'Nicholls State University' },
  'grambling|la': { city: 'Grambling', state: 'LA', students: 4072, institution: 'Grambling State University' },
  'alexandria|la': { city: 'Alexandria', state: 'LA', students: 3279, institution: 'Louisiana State University-Alexandria' },
  'amherst|ma': { city: 'Amherst', state: 'MA', students: 26109, institution: 'University of Massachusetts-Amherst' },
  'lowell|ma': { city: 'Lowell', state: 'MA', students: 13376, institution: 'University of Massachusetts-Lowell' },
  'chestnut hill|ma': { city: 'Chestnut Hill', state: 'MA', students: 9891, institution: 'Boston College' },
  'bridgewater|ma': { city: 'Bridgewater', state: 'MA', students: 9390, institution: 'Bridgewater State University' },
  'waltham|ma': { city: 'Waltham', state: 'MA', students: 7898, institution: 'Bentley University' },
  'springfield|ma': { city: 'Springfield', state: 'MA', students: 7218, institution: 'Western New England University' },
  'salem|ma': { city: 'Salem', state: 'MA', students: 6776, institution: 'Salem State University' },
  'north dartmouth|ma': { city: 'North Dartmouth', state: 'MA', students: 6559, institution: 'University of Massachusetts-Dartmouth' },
  'medford|ma': { city: 'Medford', state: 'MA', students: 6028, institution: 'Tufts University' },
  'quincy|ma': { city: 'Quincy', state: 'MA', students: 5423, institution: 'Quincy College' },
  'westfield|ma': { city: 'Westfield', state: 'MA', students: 5375, institution: 'Westfield State University' },
  'fitchburg|ma': { city: 'Fitchburg', state: 'MA', students: 4080, institution: 'Fitchburg State University' },
  'framingham|ma': { city: 'Framingham', state: 'MA', students: 4014, institution: 'Framingham State University' },
  'north andover|ma': { city: 'North Andover', state: 'MA', students: 3853, institution: 'Merrimack College' },
  'beverly|ma': { city: 'Beverly', state: 'MA', students: 3556, institution: 'Endicott College' },
  'milton|ma': { city: 'Milton', state: 'MA', students: 3404, institution: 'Curry College' },
  'newton|ma': { city: 'Newton', state: 'MA', students: 3221, institution: 'Lasell College' },
  'college park|md': { city: 'College Park', state: 'MD', students: 29273, institution: 'University of Maryland-College Park' },
  'towson|md': { city: 'Towson', state: 'MD', students: 20088, institution: 'Towson University' },
  'rockville|md': { city: 'Rockville', state: 'MD', students: 19121, institution: 'Montgomery College' },
  'salisbury|md': { city: 'Salisbury', state: 'MD', students: 7603, institution: 'Salisbury University' },
  'la plata|md': { city: 'La Plata', state: 'MD', students: 6699, institution: 'College of Southern Maryland' },
  'annapolis|md': { city: 'Annapolis', state: 'MD', students: 5129, institution: 'United States Naval Academy' },
  'bowie|md': { city: 'Bowie', state: 'MD', students: 5107, institution: 'Bowie State University' },
  'frostburg|md': { city: 'Frostburg', state: 'MD', students: 4486, institution: 'Frostburg State University' },
  'stevenson|md': { city: 'Stevenson', state: 'MD', students: 3375, institution: 'Stevenson University' },
  'orono|me': { city: 'Orono', state: 'ME', students: 8836, institution: 'University of Maine' },
  'augusta|me': { city: 'Augusta', state: 'ME', students: 3370, institution: 'University of Maine at Augusta' },
  'east lansing|mi': { city: 'East Lansing', state: 'MI', students: 39597, institution: 'Michigan State University' },
  'ann arbor|mi': { city: 'Ann Arbor', state: 'MI', students: 30452, institution: 'University of Michigan-Ann Arbor' },
  'allendale|mi': { city: 'Allendale', state: 'MI', students: 21837, institution: 'Grand Valley State University' },
  'kalamazoo|mi': { city: 'Kalamazoo', state: 'MI', students: 19240, institution: 'Western Michigan University' },
  'flint|mi': { city: 'Flint', state: 'MI', students: 19170, institution: 'Baker College' },
  'dearborn|mi': { city: 'Dearborn', state: 'MI', students: 17896, institution: 'Henry Ford College' },
  'mount pleasant|mi': { city: 'Mount Pleasant', state: 'MI', students: 17742, institution: 'Central Michigan University' },
  'rochester hills|mi': { city: 'Rochester Hills', state: 'MI', students: 16549, institution: 'Oakland University' },
  'ypsilanti|mi': { city: 'Ypsilanti', state: 'MI', students: 16536, institution: 'Eastern Michigan University' },
  'university center|mi': { city: 'University Center', state: 'MI', students: 14789, institution: 'Saginaw Valley State University' },
  'livonia|mi': { city: 'Livonia', state: 'MI', students: 11650, institution: 'Schoolcraft College' },
  'big rapids|mi': { city: 'Big Rapids', state: 'MI', students: 11549, institution: 'Ferris State University' },
  'marquette|mi': { city: 'Marquette', state: 'MI', students: 6635, institution: 'Northern Michigan University' },
  'houghton|mi': { city: 'Houghton', state: 'MI', students: 5829, institution: 'Michigan Technological University' },
  'southfield|mi': { city: 'Southfield', state: 'MI', students: 4389, institution: 'Lawrence Technological University' },
  'jackson|mi': { city: 'Jackson', state: 'MI', students: 4081, institution: 'Jackson College' },
  'adrian|mi': { city: 'Adrian', state: 'MI', students: 3798, institution: 'Siena Heights University' },
  'traverse city|mi': { city: 'Traverse City', state: 'MI', students: 3515, institution: 'Northwestern Michigan College' },
  'holland|mi': { city: 'Holland', state: 'MI', students: 3029, institution: 'Hope College' },
  'duluth|mn': { city: 'Duluth', state: 'MN', students: 15182, institution: 'University of Minnesota-Duluth' },
  'mankato|mn': { city: 'Mankato', state: 'MN', students: 12489, institution: 'Minnesota State University-Mankato' },
  'winona|mn': { city: 'Winona', state: 'MN', students: 10167, institution: 'Winona State University' },
  'saint cloud|mn': { city: 'Saint Cloud', state: 'MN', students: 9758, institution: 'Saint Cloud State University' },
  'white bear lake|mn': { city: 'White Bear Lake', state: 'MN', students: 7502, institution: 'Century College' },
  'moorhead|mn': { city: 'Moorhead', state: 'MN', students: 6814, institution: 'Minnesota State University Moorhead' },
  'northfield|mn': { city: 'Northfield', state: 'MN', students: 5027, institution: 'St Olaf College' },
  'bemidji|mn': { city: 'Bemidji', state: 'MN', students: 4493, institution: 'Bemidji State University' },
  'st. cloud|mn': { city: 'St. Cloud', state: 'MN', students: 3848, institution: 'Rasmussen College-Minnesota' },
  'columbia|mo': { city: 'Columbia', state: 'MO', students: 36270, institution: 'University of Missouri-Columbia' },
  'saint louis|mo': { city: 'Saint Louis', state: 'MO', students: 34111, institution: 'University of Missouri-St Louis' },
  'springfield|mo': { city: 'Springfield', state: 'MO', students: 23812, institution: 'Missouri State University-Springfield' },
  'parkville|mo': { city: 'Parkville', state: 'MO', students: 9442, institution: 'Park University' },
  'cape girardeau|mo': { city: 'Cape Girardeau', state: 'MO', students: 9423, institution: 'Southeast Missouri State University' },
  'warrensburg|mo': { city: 'Warrensburg', state: 'MO', students: 8612, institution: 'University of Central Missouri' },
  'rolla|mo': { city: 'Rolla', state: 'MO', students: 6953, institution: 'Missouri University of Science and Technology' },
  'saint charles|mo': { city: 'Saint Charles', state: 'MO', students: 6807, institution: 'Lindenwood University' },
  'joplin|mo': { city: 'Joplin', state: 'MO', students: 6295, institution: 'Missouri Southern State University' },
  'kirksville|mo': { city: 'Kirksville', state: 'MO', students: 5285, institution: 'Truman State University' },
  'maryville|mo': { city: 'Maryville', state: 'MO', students: 5065, institution: 'Northwest Missouri State University' },
  'saint joseph|mo': { city: 'Saint Joseph', state: 'MO', students: 4277, institution: 'Missouri Western State University' },
  'hillsboro|mo': { city: 'Hillsboro', state: 'MO', students: 4182, institution: 'Jefferson College' },
  'neosho|mo': { city: 'Neosho', state: 'MO', students: 3387, institution: 'Crowder College' },
  'oxford|ms': { city: 'Oxford', state: 'MS', students: 18537, institution: 'University of Mississippi' },
  'mississippi state|ms': { city: 'Mississippi State', state: 'MS', students: 17723, institution: 'Mississippi State University' },
  'hattiesburg|ms': { city: 'Hattiesburg', state: 'MS', students: 14222, institution: 'University of Southern Mississippi' },
  'jackson|ms': { city: 'Jackson', state: 'MS', students: 10591, institution: 'Jackson State University' },
  'alcorn state|ms': { city: 'Alcorn State', state: 'MS', students: 3172, institution: 'Alcorn State University' },
  'clinton|ms': { city: 'Clinton', state: 'MS', students: 3101, institution: 'Mississippi College' },
  'bozeman|mt': { city: 'Bozeman', state: 'MT', students: 14448, institution: 'Montana State University' },
  'missoula|mt': { city: 'Missoula', state: 'MT', students: 8958, institution: 'The University of Montana' },
  'billings|mt': { city: 'Billings', state: 'MT', students: 4469, institution: 'Montana State University Billings' },
  'greenville|nc': { city: 'Greenville', state: 'NC', students: 22790, institution: 'East Carolina University' },
  'chapel hill|nc': { city: 'Chapel Hill', state: 'NC', students: 18912, institution: 'University of North Carolina at Chapel Hill' },
  'boone|nc': { city: 'Boone', state: 'NC', students: 16888, institution: 'Appalachian State University' },
  'wilmington|nc': { city: 'Wilmington', state: 'NC', students: 16026, institution: 'University of North Carolina Wilmington' },
  'cullowhee|nc': { city: 'Cullowhee', state: 'NC', students: 9234, institution: 'Western Carolina University' },
  'fayetteville|nc': { city: 'Fayetteville', state: 'NC', students: 7857, institution: 'Fayetteville State University' },
  'elon|nc': { city: 'Elon', state: 'NC', students: 6045, institution: 'Elon University' },
  'pembroke|nc': { city: 'Pembroke', state: 'NC', students: 5308, institution: 'University of North Carolina at Pembroke' },
  'high point|nc': { city: 'High Point', state: 'NC', students: 4849, institution: 'High Point University' },
  'buies creek|nc': { city: 'Buies Creek', state: 'NC', students: 4328, institution: 'Campbell University' },
  'asheville|nc': { city: 'Asheville', state: 'NC', students: 3587, institution: 'University of North Carolina at Asheville' },
  'mount olive|nc': { city: 'Mount Olive', state: 'NC', students: 3061, institution: 'University of Mount Olive' },
  'elizabeth city|nc': { city: 'Elizabeth City', state: 'NC', students: 3019, institution: 'College of the Albemarle' },
  'fargo|nd': { city: 'Fargo', state: 'ND', students: 12455, institution: 'North Dakota State University-Main Campus' },
  'grand forks|nd': { city: 'Grand Forks', state: 'ND', students: 10392, institution: 'University of North Dakota' },
  'bismarck|nd': { city: 'Bismarck', state: 'ND', students: 5046, institution: 'Bismarck State College' },
  'lincoln|ne': { city: 'Lincoln', state: 'NE', students: 25004, institution: 'University of Nebraska-Lincoln' },
  'kearney|ne': { city: 'Kearney', state: 'NE', students: 4440, institution: 'University of Nebraska at Kearney' },
  'hanover|nh': { city: 'Hanover', state: 'NH', students: 4315, institution: 'Dartmouth College' },
  'plymouth|nh': { city: 'Plymouth', state: 'NH', students: 4072, institution: 'Plymouth State University' },
  'keene|nh': { city: 'Keene', state: 'NH', students: 3726, institution: 'Keene State College' },
  'manchester|nh': { city: 'Manchester', state: 'NH', students: 3231, institution: 'Saint Anselm College' },
  'new brunswick|nj': { city: 'New Brunswick', state: 'NJ', students: 35296, institution: 'Rutgers University-New Brunswick' },
  'montclair|nj': { city: 'Montclair', state: 'NJ', students: 16673, institution: 'Montclair State University' },
  'glassboro|nj': { city: 'Glassboro', state: 'NJ', students: 15089, institution: 'Rowan University' },
  'union|nj': { city: 'Union', state: 'NJ', students: 11982, institution: 'Kean University' },
  'wayne|nj': { city: 'Wayne', state: 'NJ', students: 9309, institution: 'William Paterson University of New Jersey' },
  'galloway|nj': { city: 'Galloway', state: 'NJ', students: 8242, institution: 'Stockton University' },
  'mount laurel|nj': { city: 'Mount Laurel', state: 'NJ', students: 8176, institution: 'Rowan College at Burlington County' },
  'ewing|nj': { city: 'Ewing', state: 'NJ', students: 6850, institution: 'The College of New Jersey' },
  'sewell|nj': { city: 'Sewell', state: 'NJ', students: 6186, institution: 'Rowan College at Gloucester County' },
  'south orange|nj': { city: 'South Orange', state: 'NJ', students: 5717, institution: 'Seton Hall University' },
  'camden|nj': { city: 'Camden', state: 'NJ', students: 5360, institution: 'Rutgers University-Camden' },
  'mahwah|nj': { city: 'Mahwah', state: 'NJ', students: 5314, institution: 'Ramapo College of New Jersey' },
  'princeton|nj': { city: 'Princeton', state: 'NJ', students: 5246, institution: 'Princeton University' },
  'lakewood|nj': { city: 'Lakewood', state: 'NJ', students: 4693, institution: 'Beth Medrash Govoha' },
  'west long branch|nj': { city: 'West Long Branch', state: 'NJ', students: 4683, institution: 'Monmouth University' },
  'lawrenceville|nj': { city: 'Lawrenceville', state: 'NJ', students: 4276, institution: 'Rider University' },
  'madison|nj': { city: 'Madison', state: 'NJ', students: 4135, institution: 'Fairleigh Dickinson University-Florham Campus' },
  'teaneck|nj': { city: 'Teaneck', state: 'NJ', students: 3550, institution: 'Fairleigh Dickinson University-Metropolitan Campus' },
  'woodland park|nj': { city: 'Woodland Park', state: 'NJ', students: 3342, institution: 'Berkeley College-Woodland Park' },
  'teterboro|nj': { city: 'Teterboro', state: 'NJ', students: 3222, institution: 'Jersey College' },
  'hoboken|nj': { city: 'Hoboken', state: 'NJ', students: 3114, institution: 'Stevens Institute of Technology' },
  'las cruces|nm': { city: 'Las Cruces', state: 'NM', students: 16773, institution: 'New Mexico State University-Main Campus' },
  'farmington|nm': { city: 'Farmington', state: 'NM', students: 5172, institution: 'San Juan College' },
  'portales|nm': { city: 'Portales', state: 'NM', students: 3431, institution: 'Eastern New Mexico University-Main Campus' },
  'carson city|nv': { city: 'Carson City', state: 'NV', students: 3000, institution: 'Western Nevada College' },
  'ithaca|ny': { city: 'Ithaca', state: 'NY', students: 20858, institution: 'Cornell University' },
  'stony brook|ny': { city: 'Stony Brook', state: 'NY', students: 17215, institution: 'Stony Brook University' },
  'vestal|ny': { city: 'Vestal', state: 'NY', students: 13702, institution: 'Binghamton University' },
  'saratoga springs|ny': { city: 'Saratoga Springs', state: 'NY', students: 11281, institution: 'SUNY Empire State College' },
  'farmingdale|ny': { city: 'Farmingdale', state: 'NY', students: 9005, institution: 'Farmingdale State College' },
  'old westbury|ny': { city: 'Old Westbury', state: 'NY', students: 8100, institution: 'SUNY College at Old Westbury' },
  'poughkeepsie|ny': { city: 'Poughkeepsie', state: 'NY', students: 7859, institution: 'Marist College' },
  'troy|ny': { city: 'Troy', state: 'NY', students: 7733, institution: 'Rensselaer Polytechnic Institute' },
  'jamaica|ny': { city: 'Jamaica', state: 'NY', students: 7281, institution: 'CUNY York College' },
  'oneonta|ny': { city: 'Oneonta', state: 'NY', students: 7154, institution: 'SUNY Oneonta' },
  'brockport|ny': { city: 'Brockport', state: 'NY', students: 7134, institution: 'SUNY College at Brockport' },
  'oswego|ny': { city: 'Oswego', state: 'NY', students: 7090, institution: 'SUNY College at Oswego' },
  'hempstead|ny': { city: 'Hempstead', state: 'NY', students: 6967, institution: 'Hofstra University' },
  'new paltz|ny': { city: 'New Paltz', state: 'NY', students: 6616, institution: 'State University of New York at New Paltz' },
  'cortland|ny': { city: 'Cortland', state: 'NY', students: 6333, institution: 'SUNY Cortland' },
  'potsdam|ny': { city: 'Potsdam', state: 'NY', students: 6287, institution: 'SUNY College at Potsdam' },
  'dobbs ferry|ny': { city: 'Dobbs Ferry', state: 'NY', students: 6029, institution: 'Mercy College' },
  'utica|ny': { city: 'Utica', state: 'NY', students: 5849, institution: 'Utica College' },
  'purchase|ny': { city: 'Purchase', state: 'NY', students: 5642, institution: 'SUNY at Purchase College' },
  'geneseo|ny': { city: 'Geneseo', state: 'NY', students: 5522, institution: 'SUNY College at Geneseo' },
  'new rochelle|ny': { city: 'New Rochelle', state: 'NY', students: 5510, institution: 'Iona College' },
  'canton|ny': { city: 'Canton', state: 'NY', students: 5440, institution: 'SUNY College of Technology at Canton' },
  'plattsburgh|ny': { city: 'Plattsburgh', state: 'NY', students: 5354, institution: 'SUNY College at Plattsburgh' },
  'alfred|ny': { city: 'Alfred', state: 'NY', students: 5286, institution: 'SUNY College of Technology at Alfred' },
  'garden city|ny': { city: 'Garden City', state: 'NY', students: 5162, institution: 'Adelphi University' },
  'orchard park|ny': { city: 'Orchard Park', state: 'NY', students: 4497, institution: 'Bryant & Stratton College-Online' },
  'west  point|ny': { city: 'West  Point', state: 'NY', students: 4491, institution: 'United States Military Academy' },
  'fredonia|ny': { city: 'Fredonia', state: 'NY', students: 4366, institution: 'SUNY at Fredonia' },
  'riverdale|ny': { city: 'Riverdale', state: 'NY', students: 3780, institution: 'Manhattan College' },
  'rockville centre|ny': { city: 'Rockville Centre', state: 'NY', students: 3505, institution: 'Molloy College' },
  'delhi|ny': { city: 'Delhi', state: 'NY', students: 3435, institution: 'SUNY College of Technology at Delhi' },
  'brookville|ny': { city: 'Brookville', state: 'NY', students: 3133, institution: 'Long Island University' },
  'loudonville|ny': { city: 'Loudonville', state: 'NY', students: 3132, institution: 'Siena College' },
  'hyde park|ny': { city: 'Hyde Park', state: 'NY', students: 3116, institution: 'Culinary Institute of America' },
  'patchogue|ny': { city: 'Patchogue', state: 'NY', students: 3037, institution: 'St. Joseph\'s College-Long Island' },
  'athens|oh': { city: 'Athens', state: 'OH', students: 22936, institution: 'Ohio University-Main Campus' },
  'kent|oh': { city: 'Kent', state: 'OH', students: 22627, institution: 'Kent State University at Kent' },
  'oxford|oh': { city: 'Oxford', state: 'OH', students: 16816, institution: 'Miami University-Oxford' },
  'bowling green|oh': { city: 'Bowling Green', state: 'OH', students: 13790, institution: 'Bowling Green State University-Main Campus' },
  'youngstown|oh': { city: 'Youngstown', state: 'OH', students: 10164, institution: 'Youngstown State University' },
  'north canton|oh': { city: 'North Canton', state: 'OH', students: 9707, institution: 'Stark State College' },
  'lima|oh': { city: 'Lima', state: 'OH', students: 7110, institution: 'University of Northwestern Ohio' },
  'canton|oh': { city: 'Canton', state: 'OH', students: 6168, institution: 'Kent State University at Stark' },
  'westerville|oh': { city: 'Westerville', state: 'OH', students: 5851, institution: 'Otterbein University' },
  'blue ash|oh': { city: 'Blue Ash', state: 'OH', students: 4495, institution: 'University of Cincinnati-Blue Ash College' },
  'ashland|oh': { city: 'Ashland', state: 'OH', students: 3704, institution: 'Ashland University' },
  'circleville|oh': { city: 'Circleville', state: 'OH', students: 3471, institution: 'Ohio Christian University' },
  'tiffin|oh': { city: 'Tiffin', state: 'OH', students: 3178, institution: 'Tiffin University' },
  'portsmouth|oh': { city: 'Portsmouth', state: 'OH', students: 3147, institution: 'Shawnee State University' },
  'cedarville|oh': { city: 'Cedarville', state: 'OH', students: 3132, institution: 'Cedarville University' },
  'berea|oh': { city: 'Berea', state: 'OH', students: 3131, institution: 'Baldwin Wallace University' },
  'norman|ok': { city: 'Norman', state: 'OK', students: 21920, institution: 'University of Oklahoma-Norman Campus' },
  'stillwater|ok': { city: 'Stillwater', state: 'OK', students: 20880, institution: 'Oklahoma State University-Main Campus' },
  'edmond|ok': { city: 'Edmond', state: 'OK', students: 16150, institution: 'University of Central Oklahoma' },
  'tahlequah|ok': { city: 'Tahlequah', state: 'OK', students: 6727, institution: 'Northeastern State University' },
  'midwest city|ok': { city: 'Midwest City', state: 'OK', students: 6091, institution: 'Rose State College' },
  'weatherford|ok': { city: 'Weatherford', state: 'OK', students: 4358, institution: 'Southwestern Oklahoma State University' },
  'lawton|ok': { city: 'Lawton', state: 'OK', students: 4332, institution: 'Cameron University' },
  'claremore|ok': { city: 'Claremore', state: 'OK', students: 3354, institution: 'Rogers State University' },
  'corvallis|or': { city: 'Corvallis', state: 'OR', students: 24980, institution: 'Oregon State University' },
  'eugene|or': { city: 'Eugene', state: 'OR', students: 19819, institution: 'University of Oregon' },
  'monmouth|or': { city: 'Monmouth', state: 'OR', students: 4747, institution: 'Western Oregon University' },
  'ashland|or': { city: 'Ashland', state: 'OR', students: 4399, institution: 'Southern Oregon University' },
  'klamath falls|or': { city: 'Klamath Falls', state: 'OR', students: 3583, institution: 'Oregon Institute of Technology' },
  'salem|or': { city: 'Salem', state: 'OR', students: 3228, institution: 'Willamette University' },
  'state college|pa': { city: 'State College', state: 'PA', students: 48661, institution: 'Pennsylvania State University-Main Campus' },
  'west chester|pa': { city: 'West Chester', state: 'PA', students: 14223, institution: 'West Chester University of Pennsylvania' },
  'bryn mawr|pa': { city: 'Bryn Mawr', state: 'PA', students: 11118, institution: 'American College of Financial Services' },
  'erie|pa': { city: 'Erie', state: 'PA', students: 10490, institution: 'Pennsylvania State University-Penn State Erie-Behrend College' },
  'indiana|pa': { city: 'Indiana', state: 'PA', students: 10060, institution: 'Indiana University of Pennsylvania-Main Campus' },
  'bloomsburg|pa': { city: 'Bloomsburg', state: 'PA', students: 8276, institution: 'Bloomsburg University of Pennsylvania' },
  'scranton|pa': { city: 'Scranton', state: 'PA', students: 7875, institution: 'University of Scranton' },
  'slippery rock|pa': { city: 'Slippery Rock', state: 'PA', students: 7539, institution: 'Slippery Rock University of Pennsylvania' },
  'kutztown|pa': { city: 'Kutztown', state: 'PA', students: 7443, institution: 'Kutztown University of Pennsylvania' },
  'bethlehem|pa': { city: 'Bethlehem', state: 'PA', students: 7377, institution: 'Lehigh University' },
  'reading|pa': { city: 'Reading', state: 'PA', students: 7321, institution: 'Pennsylvania State University-Penn State Berks' },
  'lancaster|pa': { city: 'Lancaster', state: 'PA', students: 7144, institution: 'Franklin and Marshall College' },
  'villanova|pa': { city: 'Villanova', state: 'PA', students: 6886, institution: 'Villanova University' },
  'millersville|pa': { city: 'Millersville', state: 'PA', students: 6613, institution: 'Millersville University of Pennsylvania' },
  'williamsport|pa': { city: 'Williamsport', state: 'PA', students: 6611, institution: 'Pennsylvania College of Technology' },
  'york|pa': { city: 'York', state: 'PA', students: 6523, institution: 'York College of Pennsylvania' },
  'east stroudsburg|pa': { city: 'East Stroudsburg', state: 'PA', students: 5972, institution: 'East Stroudsburg University of Pennsylvania' },
  'shippensburg|pa': { city: 'Shippensburg', state: 'PA', students: 5464, institution: 'Shippensburg University of Pennsylvania' },
  'california|pa': { city: 'California', state: 'PA', students: 5435, institution: 'California University of Pennsylvania' },
  'allentown|pa': { city: 'Allentown', state: 'PA', students: 4578, institution: 'Muhlenberg College' },
  'wilkes-barre|pa': { city: 'Wilkes-Barre', state: 'PA', students: 4569, institution: 'Wilkes University' },
  'edinboro|pa': { city: 'Edinboro', state: 'PA', students: 4229, institution: 'Edinboro University of Pennsylvania' },
  'middletown|pa': { city: 'Middletown', state: 'PA', students: 4223, institution: 'Pennsylvania State University-Penn State Harrisburg' },
  'clarion|pa': { city: 'Clarion', state: 'PA', students: 4214, institution: 'Clarion University of Pennsylvania' },
  'moon township|pa': { city: 'Moon Township', state: 'PA', students: 4213, institution: 'Robert Morris University' },
  'altoona|pa': { city: 'Altoona', state: 'PA', students: 3979, institution: 'Pennsylvania State University-Penn State Altoona' },
  'lewisburg|pa': { city: 'Lewisburg', state: 'PA', students: 3954, institution: 'Bucknell University' },
  'abington|pa': { city: 'Abington', state: 'PA', students: 3674, institution: 'Pennsylvania State University-Penn State Abington' },
  'lock haven|pa': { city: 'Lock Haven', state: 'PA', students: 3425, institution: 'Lock Haven University' },
  'greensburg|pa': { city: 'Greensburg', state: 'PA', students: 3301, institution: 'Seton Hill University' },
  'chester|pa': { city: 'Chester', state: 'PA', students: 3224, institution: 'Widener University' },
  'johnstown|pa': { city: 'Johnstown', state: 'PA', students: 3193, institution: 'University of Pittsburgh-Johnstown' },
  'center valley|pa': { city: 'Center Valley', state: 'PA', students: 3114, institution: 'DeSales University' },
  'san juan|pr': { city: 'San Juan', state: 'PR', students: 24039, institution: 'Universidad Ana G. Mendez-Cupey Campus' },
  'mayaguez|pr': { city: 'Mayaguez', state: 'PR', students: 15345, institution: 'University of Puerto Rico-Mayaguez' },
  'gurabo|pr': { city: 'Gurabo', state: 'PR', students: 14061, institution: 'Universidad Ana G. Mendez-Gurabo Campus' },
  'guaynabo|pr': { city: 'Guaynabo', state: 'PR', students: 12779, institution: 'Instituto de Banca y Comercio Inc' },
  'carolina|pr': { city: 'Carolina', state: 'PR', students: 11120, institution: 'Universidad Ana G. Mendez-Carolina Campus' },
  'ponce|pr': { city: 'Ponce', state: 'PR', students: 8406, institution: 'Pontifical Catholic University of Puerto Rico-Ponce' },
  'bayamon|pr': { city: 'Bayamon', state: 'PR', students: 8208, institution: 'Inter American University of Puerto Rico-Bayamon' },
  'aguadilla|pr': { city: 'Aguadilla', state: 'PR', students: 7644, institution: 'Inter American University of Puerto Rico-Aguadilla' },
  'caguas|pr': { city: 'Caguas', state: 'PR', students: 7235, institution: 'Mech-Tech College' },
  'hato rey|pr': { city: 'Hato Rey', state: 'PR', students: 4810, institution: 'Universidad Politecnica de Puerto Rico' },
  'arecibo|pr': { city: 'Arecibo', state: 'PR', students: 4724, institution: 'Inter American University of Puerto Rico-Arecibo' },
  'mercedita|pr': { city: 'Mercedita', state: 'PR', students: 4690, institution: 'Inter American University of Puerto Rico-Ponce' },
  'santurce|pr': { city: 'Santurce', state: 'PR', students: 4294, institution: 'Universidad del Sagrado Corazon' },
  'san german|pr': { city: 'San German', state: 'PR', students: 4046, institution: 'Inter American University of Puerto Rico-San German' },
  'kingston|ri': { city: 'Kingston', state: 'RI', students: 14008, institution: 'University of Rhode Island' },
  'bristol|ri': { city: 'Bristol', state: 'RI', students: 4476, institution: 'Roger Williams University' },
  'smithfield|ri': { city: 'Smithfield', state: 'RI', students: 3449, institution: 'Bryant University' },
  'columbia|sc': { city: 'Columbia', state: 'SC', students: 32175, institution: 'University of South Carolina-Columbia' },
  'clemson|sc': { city: 'Clemson', state: 'SC', students: 19172, institution: 'Clemson University' },
  'charleston|sc': { city: 'Charleston', state: 'SC', students: 16825, institution: 'College of Charleston' },
  'conway|sc': { city: 'Conway', state: 'SC', students: 10529, institution: 'Coastal Carolina University' },
  'spartanburg|sc': { city: 'Spartanburg', state: 'SC', students: 8953, institution: 'University of South Carolina-Upstate' },
  'greenville|sc': { city: 'Greenville', state: 'SC', students: 5900, institution: 'Furman' },
  'rock hill|sc': { city: 'Rock Hill', state: 'SC', students: 4969, institution: 'Winthrop University' },
  'orangeburg|sc': { city: 'Orangeburg', state: 'SC', students: 4529, institution: 'South Carolina State University' },
  'florence|sc': { city: 'Florence', state: 'SC', students: 3584, institution: 'Francis Marion University' },
  'aiken|sc': { city: 'Aiken', state: 'SC', students: 3095, institution: 'University of South Carolina-Aiken' },
  'brookings|sd': { city: 'Brookings', state: 'SD', students: 9704, institution: 'South Dakota State University' },
  'vermillion|sd': { city: 'Vermillion', state: 'SD', students: 6171, institution: 'University of South Dakota' },
  'rapid city|sd': { city: 'Rapid City', state: 'SD', students: 3814, institution: 'South Dakota School of Mines and Technology' },
  'sioux falls|sd': { city: 'Sioux Falls', state: 'SD', students: 3242, institution: 'Augustana University' },
  'murfreesboro|tn': { city: 'Murfreesboro', state: 'TN', students: 19544, institution: 'Middle Tennessee State University' },
  'johnson city|tn': { city: 'Johnson City', state: 'TN', students: 11116, institution: 'East Tennessee State University' },
  'clarksville|tn': { city: 'Clarksville', state: 'TN', students: 10336, institution: 'Austin Peay State University' },
  'cookeville|tn': { city: 'Cookeville', state: 'TN', students: 9582, institution: 'Tennessee Technological University' },
  'martin|tn': { city: 'Martin', state: 'TN', students: 5522, institution: 'The University of Tennessee-Martin' },
  'jackson|tn': { city: 'Jackson', state: 'TN', students: 4158, institution: 'Union University' },
  'mckenzie|tn': { city: 'Mckenzie', state: 'TN', students: 4145, institution: 'Bethel University' },
  'college station|tx': { city: 'College Station', state: 'TX', students: 52568, institution: 'Texas A & M University-College Station' },
  'denton|tx': { city: 'Denton', state: 'TX', students: 41013, institution: 'University of North Texas' },
  'lubbock|tx': { city: 'Lubbock', state: 'TX', students: 34203, institution: 'Texas Tech University' },
  'edinburg|tx': { city: 'Edinburg', state: 'TX', students: 24142, institution: 'The University of Texas Rio Grande Valley' },
  'mcallen|tx': { city: 'Mcallen', state: 'TX', students: 21152, institution: 'South Texas College' },
  'richardson|tx': { city: 'Richardson', state: 'TX', students: 19556, institution: 'The University of Texas at Dallas' },
  'huntsville|tx': { city: 'Huntsville', state: 'TX', students: 18452, institution: 'Sam Houston State University' },
  'brenham|tx': { city: 'Brenham', state: 'TX', students: 17138, institution: 'Blinn College' },
  'waco|tx': { city: 'Waco', state: 'TX', students: 14284, institution: 'Baylor University' },
  'killeen|tx': { city: 'Killeen', state: 'TX', students: 12174, institution: 'Central Texas College' },
  'beaumont|tx': { city: 'Beaumont', state: 'TX', students: 11827, institution: 'Lamar University' },
  'stephenville|tx': { city: 'Stephenville', state: 'TX', students: 11283, institution: 'Tarleton State University' },
  'mesquite|tx': { city: 'Mesquite', state: 'TX', students: 10715, institution: 'Eastfield College' },
  'nacogdoches|tx': { city: 'Nacogdoches', state: 'TX', students: 10655, institution: 'Stephen F Austin State University' },
  'farmers branch|tx': { city: 'Farmers Branch', state: 'TX', students: 10389, institution: 'Brookhaven College' },
  'gainesville|tx': { city: 'Gainesville', state: 'TX', students: 9980, institution: 'North Central Texas College' },
  'laredo|tx': { city: 'Laredo', state: 'TX', students: 9567, institution: 'Laredo College' },
  'corsicana|tx': { city: 'Corsicana', state: 'TX', students: 8968, institution: 'Navarro College' },
  'odessa|tx': { city: 'Odessa', state: 'TX', students: 8565, institution: 'Odessa College' },
  'commerce|tx': { city: 'Commerce', state: 'TX', students: 8473, institution: 'Texas A & M University-Commerce' },
  'amarillo|tx': { city: 'Amarillo', state: 'TX', students: 8014, institution: 'Amarillo College' },
  'prairie view|tx': { city: 'Prairie View', state: 'TX', students: 7975, institution: 'Prairie View A & M University' },
  'tyler|tx': { city: 'Tyler', state: 'TX', students: 7725, institution: 'The University of Texas at Tyler' },
  'baytown|tx': { city: 'Baytown', state: 'TX', students: 7579, institution: 'Lee College' },
  'levelland|tx': { city: 'Levelland', state: 'TX', students: 7431, institution: 'South Plains College' },
  'canyon|tx': { city: 'Canyon', state: 'TX', students: 7383, institution: 'West Texas A & M University' },
  'victoria|tx': { city: 'Victoria', state: 'TX', students: 6572, institution: 'University of Houston-Victoria' },
  'abilene|tx': { city: 'Abilene', state: 'TX', students: 6504, institution: 'Abilene Christian University' },
  'weatherford|tx': { city: 'Weatherford', state: 'TX', students: 6260, institution: 'Weatherford College' },
  'san angelo|tx': { city: 'San Angelo', state: 'TX', students: 5789, institution: 'Angelo State University' },
  'kingsville|tx': { city: 'Kingsville', state: 'TX', students: 5694, institution: 'Texas A & M University-Kingsville' },
  'kilgore|tx': { city: 'Kilgore', state: 'TX', students: 5680, institution: 'Kilgore College' },
  'wichita falls|tx': { city: 'Wichita Falls', state: 'TX', students: 5329, institution: 'Midwestern State University' },
  'lancaster|tx': { city: 'Lancaster', state: 'TX', students: 5176, institution: 'Cedar Valley College' },
  'temple|tx': { city: 'Temple', state: 'TX', students: 4930, institution: 'Temple College' },
  'brownsville|tx': { city: 'Brownsville', state: 'TX', students: 4556, institution: 'Texas Southmost College' },
  'texarkana|tx': { city: 'Texarkana', state: 'TX', students: 4094, institution: 'Texarkana College' },
  'midland|tx': { city: 'Midland', state: 'TX', students: 3983, institution: 'Midland College' },
  'universal city|tx': { city: 'Universal City', state: 'TX', students: 3779, institution: 'Northeast Lakeview College' },
  'lufkin|tx': { city: 'Lufkin', state: 'TX', students: 3642, institution: 'Angelina College' },
  'plainview|tx': { city: 'Plainview', state: 'TX', students: 3549, institution: 'Wayland Baptist University' },
  'belton|tx': { city: 'Belton', state: 'TX', students: 3275, institution: 'University of Mary Hardin-Baylor' },
  'cisco|tx': { city: 'Cisco', state: 'TX', students: 3160, institution: 'Cisco College' },
  'lake jackson|tx': { city: 'Lake Jackson', state: 'TX', students: 3058, institution: 'Brazosport College' },
  'denison|tx': { city: 'Denison', state: 'TX', students: 3051, institution: 'Grayson College' },
  'texas city|tx': { city: 'Texas City', state: 'TX', students: 3047, institution: 'College of the Mainland' },
  'provo|ut': { city: 'Provo', state: 'UT', students: 32142, institution: 'Brigham Young University-Provo' },
  'orem|ut': { city: 'Orem', state: 'UT', students: 27972, institution: 'Utah Valley University' },
  'logan|ut': { city: 'Logan', state: 'UT', students: 21652, institution: 'Utah State University' },
  'ogden|ut': { city: 'Ogden', state: 'UT', students: 17095, institution: 'Weber State University' },
  'saint george|ut': { city: 'Saint George', state: 'UT', students: 7777, institution: 'Dixie State University' },
  'cedar city|ut': { city: 'Cedar City', state: 'UT', students: 6897, institution: 'Southern Utah University' },
  'ephraim|ut': { city: 'Ephraim', state: 'UT', students: 3471, institution: 'Snow College' },
  'blacksburg|va': { city: 'Blacksburg', state: 'VA', students: 27120, institution: 'Virginia Polytechnic Institute and State University' },
  'fairfax|va': { city: 'Fairfax', state: 'VA', students: 26285, institution: 'George Mason University' },
  'harrisonburg|va': { city: 'Harrisonburg', state: 'VA', students: 20755, institution: 'James Madison University' },
  'charlottesville|va': { city: 'Charlottesville', state: 'VA', students: 16267, institution: 'University of Virginia-Main Campus' },
  'radford|va': { city: 'Radford', state: 'VA', students: 8376, institution: 'Radford University' },
  'williamsburg|va': { city: 'Williamsburg', state: 'VA', students: 6243, institution: 'College of William and Mary' },
  'newport news|va': { city: 'Newport News', state: 'VA', students: 5480, institution: 'Christopher Newport University' },
  'fredericksburg|va': { city: 'Fredericksburg', state: 'VA', students: 4551, institution: 'University of Mary Washington' },
  'petersburg|va': { city: 'Petersburg', state: 'VA', students: 4265, institution: 'Virginia State University' },
  'farmville|va': { city: 'Farmville', state: 'VA', students: 4230, institution: 'Longwood University' },
  'hampton|va': { city: 'Hampton', state: 'VA', students: 4148, institution: 'Hampton University' },
  'lexington|va': { city: 'Lexington', state: 'VA', students: 3541, institution: 'Washington and Lee University' },
  'lynchburg|va': { city: 'Lynchburg', state: 'VA', students: 3260, institution: 'University of Lynchburg' },
  'university of richmond|va': { city: 'University Of Richmond', state: 'VA', students: 3165, institution: 'University of Richmond' },
  'burlington|vt': { city: 'Burlington', state: 'VT', students: 14284, institution: 'University of Vermont' },
  'northfield|vt': { city: 'Northfield', state: 'VT', students: 3160, institution: 'Norwich University' },
  'pullman|wa': { city: 'Pullman', state: 'WA', students: 24797, institution: 'Washington State University' },
  'bellingham|wa': { city: 'Bellingham', state: 'WA', students: 15364, institution: 'Western Washington University' },
  'ellensburg|wa': { city: 'Ellensburg', state: 'WA', students: 11468, institution: 'Central Washington University' },
  'vancouver|wa': { city: 'Vancouver', state: 'WA', students: 11065, institution: 'Clark College' },
  'cheney|wa': { city: 'Cheney', state: 'WA', students: 10500, institution: 'Eastern Washington University' },
  'lakewood|wa': { city: 'Lakewood', state: 'WA', students: 8748, institution: 'Pierce College-Fort Steilacoom' },
  'bothell|wa': { city: 'Bothell', state: 'WA', students: 7611, institution: 'University of Washington-Bothell Campus' },
  'bellevue|wa': { city: 'Bellevue', state: 'WA', students: 7223, institution: 'Bellevue College' },
  'pasco|wa': { city: 'Pasco', state: 'WA', students: 5731, institution: 'Columbia Basin College' },
  'auburn|wa': { city: 'Auburn', state: 'WA', students: 5680, institution: 'Green River College' },
  'bremerton|wa': { city: 'Bremerton', state: 'WA', students: 4627, institution: 'Olympic College' },
  'olympia|wa': { city: 'Olympia', state: 'WA', students: 3660, institution: 'The Evergreen State College' },
  'kirkland|wa': { city: 'Kirkland', state: 'WA', students: 3253, institution: 'Lake Washington Institute of Technology' },
  'madison|wi': { city: 'Madison', state: 'WI', students: 42876, institution: 'University of Wisconsin-Madison' },
  'la crosse|wi': { city: 'La Crosse', state: 'WI', students: 11203, institution: 'University of Wisconsin-La Crosse' },
  'whitewater|wi': { city: 'Whitewater', state: 'WI', students: 10543, institution: 'University of Wisconsin-Whitewater' },
  'eau claire|wi': { city: 'Eau Claire', state: 'WI', students: 10116, institution: 'University of Wisconsin-Eau Claire' },
  'oshkosh|wi': { city: 'Oshkosh', state: 'WI', students: 9187, institution: 'University of Wisconsin-Oshkosh' },
  'menomonie|wi': { city: 'Menomonie', state: 'WI', students: 7955, institution: 'University of Wisconsin-Stout' },
  'stevens point|wi': { city: 'Stevens Point', state: 'WI', students: 7768, institution: 'University of Wisconsin-Stevens Point' },
  'platteville|wi': { city: 'Platteville', state: 'WI', students: 7496, institution: 'University of Wisconsin-Platteville' },
  'kenosha|wi': { city: 'Kenosha', state: 'WI', students: 7149, institution: 'University of Wisconsin-Parkside' },
  'green bay|wi': { city: 'Green Bay', state: 'WI', students: 6592, institution: 'University of Wisconsin-Green Bay' },
  'river falls|wi': { city: 'River Falls', state: 'WI', students: 5515, institution: 'University of Wisconsin-River Falls' },
  'mequon|wi': { city: 'Mequon', state: 'WI', students: 3533, institution: 'Concordia University-Wisconsin' },
  'morgantown|wv': { city: 'Morgantown', state: 'WV', students: 21964, institution: 'West Virginia University' },
  'huntington|wv': { city: 'Huntington', state: 'WV', students: 8630, institution: 'Marshall University' },
  'fairmont|wv': { city: 'Fairmont', state: 'WV', students: 3539, institution: 'Fairmont State University' },
  'laramie|wy': { city: 'Laramie', state: 'WY', students: 10087, institution: 'University of Wyoming' },
}

const CITY_ALIASES: Record<string, string> = {
  'state college|pa': 'university park|pa',
  'oxford|ms': 'university|ms',
}

/**
 * Looks up whether a lead's city/state matches a known college town.
 * Returns null (not undefined) on no match — this is a lookup, not a
 * screen. Non-matching leads are NOT discarded here or anywhere in the
 * pipeline; the scorer uses this to rank, never to drop a lead.
 * Gateway markets are excluded from this table by design (see header).
 */
export function matchCollegeTown(city: string | undefined | null, state: string | undefined | null): CollegeTownMatch | null {
  if (!city || !state) return null
  const key = city.trim().toLowerCase() + '|' + state.trim().toLowerCase()
  if (COLLEGE_TOWNS[key]) return COLLEGE_TOWNS[key]
  const aliasKey = CITY_ALIASES[key]
  if (aliasKey && COLLEGE_TOWNS[aliasKey]) return COLLEGE_TOWNS[aliasKey]
  return null
}
